name: Run all tests
on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review, review_requested, reopened]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the project dependencies and the `mdframe` package
        run: poetry install
      - name: Run all tests under Coverage
        run: poetry run coverage run -m pytest
      - name: Create XML coverage report
        run: poetry run coverage xml
      - name: Generate coverage report
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check style with pylint
        run: |
          """
            for d in *; do
              pylint $d
            done
          """