name: Run all tests
on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review, review_requested, reopened]

jobs:
  run-pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the project dependencies and the `mdframe` package
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check style with pylint
        run: poetry run pylint $(git ls-files '*.py')
