name: Run all tests
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the project dependencies and the `mdframe` package
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest