gid = 6
uid = "d7a896e3-1c75-47a1-bd3e-730f378f6240"

[item]
nutrition_subgroup = "cookies and brownies"
food_type = "brownie"
description = "very tasty"

[metrics]
weight = 101
unit = "g"

[model]
project_name = "Project09172023160310"
rgbd_file_names = [
    "6_brownie_2_0",
    "6_brownie_2_1",
]
quality = 3
quality_comments = "very high quality"

[time]
started = "16:00:54"
finished = "16:10:19"

[[qa]]
done = true
rgbd_files_present = true
model_quality_acceptable = true
rgbd_quality_acceptable = false
ingredients_acceptable = true

comments = """
RGBD files: unacceptable, only 2-3 sides are represented on the video capture.
Brownie captures are also without the unique-frame markers.
Model quality: great
"""
model_merge_required = false
model_texture_required = true
accepted = false