gid = 27
uid = "4cf7b0b8-1c4d-4579-a934-7c22f60148d0"

[item]
nutrition_subgroup = "other sandwiches"
food_type = "sandwich"
description = "dempsters whole grain bread + ham"

[metrics]
weight = 117
unit = "g"
ingredients = [
    {name = "cheese", weight = 22},
    {name = "ham slice", weight = 12},
    {name = "lettuce", weight = 7},
    {name = "buns", weight = 76},
]

[model]
project_name = "Project10202023214419"
rgbd_file_names = [
    "27_sandwich_4_0",
    "27_sandwich_4_1",
]
nutrition_facts_sources = [
    
]
quality = 3
quality_comments = "need to merge on meshlab"
merged = false

[time]
started = "17:39:13"
finished = "18:10:36"

[[qa]]
done = true
rgbd_files_present = true
model_quality_acceptable = false
rgbd_quality_acceptable = true
ingredients_acceptable = true

comments = """
RGBD files: ok
Model quality: requires merging
"""
model_merge_required = true
model_texture_required = true
accepted = false
