gid = 36
uid = "fa252054-27bc-4806-90b1-15c46504747e"

[item]
nutrition_subgroup = "melons"
food_type = "melon"
description = "watermelon"

[metrics]
weight = 20
unit = "g"
ingredients = [
    
]

[model]
project_name = "Project10262023160743"
rgbd_file_names = [
    "36_melon_7_0",
    "36_melon_7_1",
]
nutrition_facts_sources = [
    
]

quality = 2
quality_comments = "individual scans look alright, but unable to merge (use meshlab)"
merged = false

[time]
started = "16:06:41"
finished = "16:37:32"

[[qa]]
done = true
rgbd_files_present = true
model_quality_acceptable = true
rgbd_quality_acceptable = true
ingredients_acceptable = true
comments = """
RGBD files: very good
Model quality:  requires merging
"""
model_merge_required = true
model_texture_required = true
accepted = false