gid = 52
uid = "9bbace69-1cb4-486d-90b8-23de6edb83d3"

[item]
nutrition_subgroup = "tortilla and corn chips"
food_type = "tortilla and corn chips"
description = "single organic gluten free salted stone ground tortilla chip"

[metrics]
weight = 3
unit = "g"
ingredients = [
    
]

[model]
project_name = "Project11192023154526"
rgbd_file_names = [
    "52_tortillacornchips_1_0",
    "52_tortillacornchips_1_1",
]
nutrition_facts_sources = [
    "IMG_7087"
]

texture_sources = [
    "IMG_7093",
    "IMG_7094",
    "IMG_7095",
    "IMG_7096",
    "IMG_7097",
    "IMG_7098"
]

quality = 2
quality_comments = "texturing function works very well and creates a very accurate image, but couldn't merge properly"
merged = false
textured = true

[time]
started = "15:04:33"
finished = "15:55:42"

[[qa]]
done = true
rgbd_files_present = true
model_quality_acceptable = true
rgbd_quality_acceptable = true
ingredients_acceptable = true
comments = """
RGBD files: very good
Model quality:  requires merging
"""
model_merge_required = true
model_texture_required = true
accepted = false